### ISSUE TITLE
能不能介绍下dsm docker下具体使用方法，谢谢

### ISSUE THREAD

**Issue by qwer0123** [VAllens/Allen.AliyunDDNSClient#2]
如题

**Comment by VAllens** [comment]
前提：
1.会docker命令。
2.会SSH命令。
3.有DSM操作系统主机（例如白群晖或黑群晖，并且里面安装有Docker）,此项可选，如果你有任意一台24小时开着的并且装有Docker的也可以。
4.有在阿里云(万网)的域名。
5.成为阿里云开发者，获取相关授权KEY.
6.拉取本项目源代码。
正文：
找到并且修改DdnsClient.json里的参数，通常你只需要修改AccessKeyId，AccessKeySecret，DomainRecords参数就可以了。
然后编译项目，并且发布到本地，以及用docker打包镜像....

**Comment by qwer0123** [comment]
构建的时候执行失败
lstat obj/Docker/publish: no such file or directory
是什么原因？

**Comment by VAllens** [comment]
详细说说你的操作步骤以及所有相关工具环境的版本，最好附上截图和操作命令/代码。
如果有需要，我可以远程帮你看看

**Comment by VAllens** [comment]
The questioner does not have any further feedback, so closed the issue.
